### ISSUE TITLE
Consider using an API for the data?

### ISSUE THREAD

**Issue by sjagoori** [sjagoori/dating-app#28]
https://github.com/sjagoori/dating-app/blob/10814ae2a537cd61d650260449e8ea3ebf5fcf39/public/dummyContent.js#L4

Might be a cleaner solution do fetch names from an API, what do you think?

**Comment by SjorsWijsman** [comment]
I kinda liked not having to add another third party dependency

**Comment by sjagoori** [comment]
Why not?

**Comment by SjorsWijsman** [comment]
Local should be slightly faster than calling an API for every time a new name needs to be generated and it's dummy content after all.

**Comment by sjagoori** [comment]
Makes sense 👍  good job
